### ISSUE TITLE
kri - Quaternions.wiki

### ISSUE THREAD

**Issue by christofelfferich** [kvark/kri#39]
Good day, I have a question about the excellent kri Quaternions.wiki on google code and didn't find a better way than looking for an answer here. First the use proj_cam is not entirely clear. x and y seem for scaling, z and w remain unclear. I'm trying to achieve lighting in a fragment shader with the v2light and v2cam in tangent space, without use of normal or tangent attributes. It is also not clear how to manipulate gl_FragColor. Would this be the right place for my question? Many thanks.

**Comment by kvark** [comment]
Ah, you made me realize I left all the wiki in there, and the export function no longer works :(
Rendering on google code is also broken, sad.

The `proj_cam` is encoded as: XYZ = scale of xyz, W = offset of z. This encodes a centered symmetric perspective projection.

Ideally, you could jump on "#gfx:matrix.org" (Matrix room) or reach out to me there ("@kvark:matrix.org") to chat. Issues are not created for that.

**Comment by christofelfferich** [comment]
Thanks much for the info. I got it right now. The quaternions wiki really have been a help figuring out the vertex shader.
